version: "3.2"
services:
  database:
    container_name: soccer-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/demo/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/demo/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/demo/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=soccerdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - test_env

  application:
    container_name: soccer-application-container
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://soccer-container:3306/soccerdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - test_env

networks:
  test_env:
    driver: bridge